server.port=6110
spring.application.name=rapportActivity

# MySQL Configuration for rapportActivity
spring.datasource.url=jdbc:mysql://localhost:3306/sr_rapportactivity?serverTimezone=Africa/Casablanca
spring.datasource.username=root
spring.datasource.password=root123

# Hibernate and JPA Settings
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Other Spring Settings
spring.main.banner-mode=off
spring.thymeleaf.cache=false
